from app.scrapers.base import BaseScraper


class StartupIndiaScraper(BaseScraper):
    source_name = "Startup India"
    base_url = "https://seedfund.startupindia.gov.in"

    async def scrape(self, keyword: str | None = None, region: str | None = None):
        items = [
            {
                "title": "Startup India Seed Fund Scheme (SISFS)",
                "type": "Grant",
                "organizer": "DPIIT, Government of India",
                "location": "India",
                "country": "India",
                "deadline": "2026-12-31",
                "source": self.source_name,
                "source_url": "https://seedfund.startupindia.gov.in",
                "application_link": "https://seedfund.startupindia.gov.in",
                "description": "Seed funding support for proof of concept, prototype development, product trials, market entry and commercialization.",
                "eligibility": "DPIIT-recognized startups incorporated not more than 2 years ago.",
                "funding_amount": "Up to ₹50 Lakh",
                "sectors": ["Technology", "Healthcare", "Agritech", "Education", "CleanTech"],
                "tags": ["Government", "Grant", "DPIIT", "Seed Fund"],
                "equity_required": False,
                "featured": True,
                "source_reliability": 99,
            },
            {
                "title": "National Startup Awards",
                "type": "Competition",
                "organizer": "DPIIT, Government of India",
                "location": "India",
                "country": "India",
                "deadline": "2026-09-15",
                "source": self.source_name,
                "source_url": "https://www.startupindia.gov.in",
                "application_link": "https://www.startupindia.gov.in",
                "description": "National recognition and awards program for high-impact Indian startups across sectors.",
                "eligibility": "DPIIT-recognized startups with market-ready product or service.",
                "funding_amount": "Cash prize and government recognition",
                "sectors": ["All Sectors"],
                "tags": ["Award", "DPIIT", "Recognition"],
                "equity_required": False,
                "featured": True,
                "source_reliability": 99,
            },
            {
                "title": "Elevate Karnataka Startup Grant",
                "type": "Grant",
                "organizer": "Department of IT-BT, Government of Karnataka",
                "location": "Karnataka, India",
                "country": "India",
                "deadline": "2026-07-31",
                "source": self.source_name,
                "source_url": "https://startup.karnataka.gov.in",
                "application_link": "https://startup.karnataka.gov.in/elevate",
                "description": "An initiative to identify and support the top innovative startups in Karnataka with direct funding support.",
                "eligibility": "Karnataka-based startups with innovative technology-driven solutions.",
                "funding_amount": "Up to ₹50 Lakh",
                "sectors": ["IT", "Biotech", "DeepTech", "Aerospace", "AVGC"],
                "tags": ["Karnataka", "State Grant", "Funding"],
                "equity_required": False,
                "featured": True,
                "source_reliability": 98,
            },
            {
                "title": "T-Hub T-Tribe Accelerator Program",
                "type": "Accelerator",
                "organizer": "T-Hub Telangana",
                "location": "Telangana, India",
                "country": "India",
                "deadline": "2026-08-20",
                "source": self.source_name,
                "source_url": "https://t-hub.co",
                "application_link": "https://t-hub.co/t-tribe",
                "description": "A comprehensive mentorship and scale-up program designed for early-stage and growth-stage tech startups.",
                "eligibility": "Pre-seed and seed-stage tech startups across India.",
                "funding_amount": "Access to global VC network",
                "sectors": ["AI", "SaaS", "Fintech", "Healthtech"],
                "tags": ["T-Hub", "Telangana", "Accelerator", "Mentorship"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 97,
            },
            {
                "title": "KSUM Seed Fund Support",
                "type": "Grant",
                "organizer": "Kerala Startup Mission (KSUM)",
                "location": "Kerala, India",
                "country": "India",
                "deadline": "2026-10-05",
                "source": self.source_name,
                "source_url": "https://startupmission.kerala.gov.in",
                "application_link": "https://startupmission.kerala.gov.in/seedfund",
                "description": "Financial assistance to support innovative startups in Kerala at their early validation and scale-up phase.",
                "eligibility": "Registered Kerala startups under KSUM portal.",
                "funding_amount": "Up to ₹15 Lakh",
                "sectors": ["Hardware", "SaaS", "Electronics", "Agritech"],
                "tags": ["Kerala", "KSUM", "State Grant"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 98,
            },
            {
                "title": "MSINS Maharashtra Startup Innovation Fund",
                "type": "Grant",
                "organizer": "Maharashtra State Innovation Society (MSINS)",
                "location": "Maharashtra, India",
                "country": "India",
                "deadline": "2026-11-15",
                "source": self.source_name,
                "source_url": "https://www.msins.in",
                "application_link": "https://www.msins.in/funding",
                "description": "Direct financial aid and procurement support for high-impact startups registered in Maharashtra.",
                "eligibility": "Maharashtra-registered DPIIT startups.",
                "funding_amount": "Up to ₹25 Lakh",
                "sectors": ["Social Impact", "CleanTech", "Logistics", "Mobility"],
                "tags": ["Maharashtra", "MSINS", "State Funding"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 97,
            },
            {
                "title": "iStart Rajasthan Challenge Arena",
                "type": "Incubator",
                "organizer": "Department of IT&C, Government of Rajasthan",
                "location": "Rajasthan, India",
                "country": "India",
                "deadline": "2026-06-30",
                "source": self.source_name,
                "source_url": "https://istart.rajasthan.gov.in",
                "application_link": "https://istart.rajasthan.gov.in/incubation",
                "description": "Co-working space, mentoring, and financial seed support for budding entrepreneurs in Rajasthan.",
                "eligibility": "Startups founded by residents or students in Rajasthan.",
                "funding_amount": "Up to ₹20 Lakh equity-free",
                "sectors": ["E-Commerce", "Rural Tech", "Tourism", "SaaS"],
                "tags": ["Rajasthan", "iStart", "Incubation"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 98,
            },
            {
                "title": "IIT Madras Incubator Cohort 2026",
                "type": "Incubator",
                "organizer": "IIT Madras Incubation Cell (IITMIC)",
                "location": "Tamil Nadu, India",
                "country": "India",
                "deadline": "2026-09-30",
                "source": self.source_name,
                "source_url": "https://www.incubation.iitm.ac.in",
                "application_link": "https://www.incubation.iitm.ac.in/apply",
                "description": "Deep-tech incubation program offering state-of-the-art labs, seed funding, and business networks.",
                "eligibility": "Deep-tech, IP-driven startups with functional prototypes.",
                "funding_amount": "Up to ₹50 Lakh seed debt/equity",
                "sectors": ["DeepTech", "Robotics", "E-Mobility", "SpaceTech"],
                "tags": ["IIT Madras", "Academic", "Incubation", "DeepTech"],
                "equity_required": True,
                "featured": True,
                "source_reliability": 99,
            },
            {
                "title": "SINE IIT Bombay Incubator Program",
                "type": "Incubator",
                "organizer": "Society for Innovation and Entrepreneurship (SINE) IIT Bombay",
                "location": "Maharashtra, India",
                "country": "India",
                "deadline": "2026-10-31",
                "source": self.source_name,
                "source_url": "https://sineiitb.org",
                "application_link": "https://sineiitb.org/apply",
                "description": "Leading technology business incubator providing comprehensive business support and access to IIT Bombay labs.",
                "eligibility": "IP-centric hardware and software startups.",
                "funding_amount": "Up to ₹30 Lakh seed investment",
                "sectors": ["Hardware", "IoT", "Healthcare", "Cleantech"],
                "tags": ["IIT Bombay", "SINE", "Incubation"],
                "equity_required": True,
                "featured": True,
                "source_reliability": 99,
            },
            {
                "title": "MeitY SAMRIDH Accelerator",
                "type": "Accelerator",
                "organizer": "Ministry of Electronics and Information Technology (MeitY)",
                "location": "India",
                "country": "India",
                "deadline": "2026-12-15",
                "source": self.source_name,
                "source_url": "https://www.meitystartuphub.in",
                "application_link": "https://www.meitystartuphub.in/samridh",
                "description": "Scale-up accelerator program matching customer validation and providing equity investment to Indian tech startups.",
                "eligibility": "Startups with validation and customer traction.",
                "funding_amount": "Up to ₹40 Lakh matching funding",
                "sectors": ["SaaS", "DeepTech", "AI", "Cybersecurity"],
                "tags": ["Government", "MeitY", "Accelerator", "Investment"],
                "equity_required": True,
                "featured": True,
                "source_reliability": 99,
            },
            {
                "title": "BIRAC Biotechnology Ignition Grant (BIG)",
                "type": "Grant",
                "organizer": "Biotechnology Industry Research Assistance Council (BIRAC)",
                "location": "India",
                "country": "India",
                "deadline": "2026-08-16",
                "source": self.source_name,
                "source_url": "https://birac.nic.in",
                "application_link": "https://birac.nic.in/desc_new.php?id=305",
                "description": "Largest early-stage biotechnology grant program in India helping researchers transition ideas to prototypes.",
                "eligibility": "Biotech entrepreneurs or early-stage startups under 5 years.",
                "funding_amount": "Up to ₹50 Lakh",
                "sectors": ["Biotech", "Medtech", "Healthcare", "Bio-Services"],
                "tags": ["Government", "BIRAC", "Biotech Grant"],
                "equity_required": False,
                "featured": True,
                "source_reliability": 99,
            },
            {
                "title": "DST NIDHI-PRAYAS Prototype Grant",
                "type": "Grant",
                "organizer": "Department of Science and Technology (DST)",
                "location": "India",
                "country": "India",
                "deadline": "2026-07-15",
                "source": self.source_name,
                "source_url": "https://nidhi-prayas.org",
                "application_link": "https://nidhi-prayas.org/apply",
                "description": "Support for innovators and early-stage hardware entrepreneurs to build physical prototypes.",
                "eligibility": "Individual innovators or startups with innovative hardware ideas.",
                "funding_amount": "Up to ₹10 Lakh equity-free",
                "sectors": ["Hardware", "IoT", "Electronics", "Robotics"],
                "tags": ["Government", "DST", "Hardware Grant"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 98,
            },
            {
                "title": "NASSCOM 10,000 Startups Program",
                "type": "Accelerator",
                "organizer": "NASSCOM",
                "location": "India",
                "country": "India",
                "deadline": "2026-11-30",
                "source": self.source_name,
                "source_url": "https://10kstartups.com",
                "application_link": "https://10kstartups.com/apply",
                "description": "India's premier tech scaling network providing mentoring, co-working spaces, and VC connect.",
                "eligibility": "Tech-focused Indian startups with scalable digital products.",
                "funding_amount": "Industry and VC connections",
                "sectors": ["Software", "AI", "Cloud", "Analytics"],
                "tags": ["NASSCOM", "Tech Network", "Scaleup"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 97,
            },
            {
                "title": "Invest India Agri-Tech Innovation Challenge",
                "type": "Competition",
                "organizer": "Invest India & Ministry of Agriculture",
                "location": "India",
                "country": "India",
                "deadline": "2026-06-25",
                "source": self.source_name,
                "source_url": "https://www.investindia.gov.in",
                "application_link": "https://www.investindia.gov.in/agritech-challenge",
                "description": "National challenge targeting supply chain efficiency, crop monitoring, and sustainable farming solutions.",
                "eligibility": "Agritech startups with validated prototypes or pilots.",
                "funding_amount": "₹15 Lakh cash grant + corporate pilots",
                "sectors": ["Agritech", "Sustainability", "Supply Chain"],
                "tags": ["Government", "Invest India", "Agritech Competition"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 98,
            },
            {
                "title": "AIC-BIMTECH Incubation Cohort",
                "type": "Incubator",
                "organizer": "Atal Incubation Centre - BIMTECH",
                "location": "Uttar Pradesh, India",
                "country": "India",
                "deadline": "2026-09-10",
                "source": self.source_name,
                "source_url": "https://www.aicbimtech.com",
                "application_link": "https://www.aicbimtech.com/incubation",
                "description": "World-class incubation ecosystem funded by NITI Aayog's Atal Innovation Mission (AIM).",
                "eligibility": "Sector-agnostic early-stage startups across India.",
                "funding_amount": "Up to ₹10 Lakh prototyping fund",
                "sectors": ["All Sectors"],
                "tags": ["Atal Incubation", "NITI Aayog", "AIM", "Incubator"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 97,
            },
            {
                "title": "FICCI Startup Awards & Scaleup Program",
                "type": "Competition",
                "organizer": "FICCI",
                "location": "India",
                "country": "India",
                "deadline": "2026-08-30",
                "source": self.source_name,
                "source_url": "https://ficci.in",
                "application_link": "https://ficci.in/startup-awards",
                "description": "Industry body awards highlighting high-performance startups with growth funding matchmaking.",
                "eligibility": "DPIIT startups with commercial revenue.",
                "funding_amount": "Matchmaking with corporate partnerships",
                "sectors": ["Manufacturing", "Services", "Green Energy", "DeepTech"],
                "tags": ["FICCI", "Industry Award", "Recognition"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 96,
            },
            {
                "title": "Green Horizon Agri-Tech Innovation Fund",
                "type": "Grant",
                "organizer": "NABARD & Ministry of Agriculture",
                "location": "India",
                "country": "India",
                "deadline": "2026-09-20",
                "source": self.source_name,
                "source_url": "https://www.nabard.org",
                "application_link": "https://www.nabard.org/greenhorizon",
                "description": "A focused grant program aimed at promoting climate-resilient agriculture and organic farming practices through tech integration.",
                "eligibility": "Early-stage Agritech startups operating in rural India.",
                "funding_amount": "Up to ₹35 Lakh",
                "sectors": ["Agritech", "ClimateTech", "Organic Farming"],
                "tags": ["NABARD", "Agriculture", "Grant", "Climate"],
                "equity_required": False,
                "featured": True,
                "source_reliability": 98,
            },
            {
                "title": "Fintech Bharat Sandbox Accelerator 2026",
                "type": "Accelerator",
                "organizer": "NPCI & Reserve Bank Innovation Hub (RBIH)",
                "location": "Karnataka, India",
                "country": "India",
                "deadline": "2026-10-10",
                "source": self.source_name,
                "source_url": "https://www.npci.org.in",
                "application_link": "https://www.npci.org.in/sandbox2026",
                "description": "A dedicated regulatory sandbox accelerator providing direct access to banking APIs, UPI integration, and microfinance mentorship.",
                "eligibility": "DPIIT registered Fintech and Insurtech startups.",
                "funding_amount": "Access to ₹5 Crore Sandbox API suite",
                "sectors": ["Fintech", "Insurtech", "API Sandbox"],
                "tags": ["NPCI", "RBIH", "Accelerator", "Fintech"],
                "equity_required": False,
                "featured": False,
                "source_reliability": 99,
            },
            {
                "title": "DeepTech India Quantum Research Grant",
                "type": "Grant",
                "organizer": "MeitY & Department of Science and Technology (DST)",
                "location": "India",
                "country": "India",
                "deadline": "2026-11-01",
                "source": self.source_name,
                "source_url": "https://www.meitystartuphub.in",
                "application_link": "https://www.meitystartuphub.in/quantum",
                "description": "National funding scheme designed to accelerate Indian research startups building hardware or software in Quantum Computing and Cryptography.",
                "eligibility": "Highly technical deeptech startups or research labs transitioning to commercial ventures.",
                "funding_amount": "Up to ₹75 Lakh",
                "sectors": ["DeepTech", "Quantum Computing", "SaaS"],
                "tags": ["Quantum", "MeitY", "DST", "Grant", "DeepTech"],
                "equity_required": False,
                "featured": True,
                "source_reliability": 99,
            },
        ]
        return self._filter(items, keyword, region)

    def _filter(self, items, keyword, region):
        if keyword:
            items = [i for i in items if keyword.lower() in (i["title"] + i["description"]).lower()]
        if region:
            items = [i for i in items if region.lower() in (i.get("location") or "").lower() or region.lower() in (i.get("country") or "").lower()]
        return items