seed_records = [
    {
        "title": "Startup India Seed Fund Scheme (SISFS)",
        "type": "Grant",
        "organizer": "DPIIT, Government of India",
        "location": "India",
        "country": "India",
        "source": "Startup India",
        "source_url": "https://seedfund.startupindia.gov.in",
        "application_link": "https://seedfund.startupindia.gov.in",
        "description": "Seed funding support for early-stage startups.",
        "funding_amount": "Up to ₹50 Lakh",
        "sectors": ["Technology", "AI", "HealthTech"],
        "tags": ["Government", "Grant", "DPIIT"],
        "equity_required": False,
        "featured": True,
        "source_reliability": 99,
    },
    {
        "title": "Google for Startups Accelerator India",
        "type": "Accelerator",
        "organizer": "Google",
        "location": "Bangalore / Remote",
        "country": "India",
        "source": "Google for Startups",
        "source_url": "https://startup.google.com",
        "application_link": "https://startup.google.com",
        "description": "Equity-free accelerator with cloud credits and AI mentorship.",
        "funding_amount": "$100K+ Cloud Credits",
        "sectors": ["AI", "SaaS", "Cloud"],
        "tags": ["Google", "Cloud Credits"],
        "equity_required": False,
        "featured": True,
        "source_reliability": 99,
    },
]